development:
  adapter: postgresql
  encoding: unicode
  database: gm_development

test:
  adapter: postgresql
  encoding: unicode
  database: gm_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gm
  pool: 5
